### ISSUE TITLE
Mix with Music from other apps

### ISSUE THREAD

**Issue by maitycyrus** [ukasz123/soundpool#102]
If, I open my flutter app using soundpool all other sounds of all other apps stop playing. 

Simple Use case: I want to listen to Spotify during using my flutter app.

Is that even possible with the soundpool package? Ohter, packages have some "Mix with audio" parameter. Is there something similar?

**Comment by maitycyrus** [comment]
`SoundpoolOptionsIos(audioSessionCategory: AudioSessionCategory.ambient))` does the trick

**Comment by yelkamel** [comment]
I did that and I still have my music get stop when play that

**Comment by Bolling88** [comment]
I have the same issue
