### ISSUE TITLE
Catch when the sound is completed.

### ISSUE THREAD

**Issue by chrislaurie-io** [ukasz123/soundpool#109]
When I invoke pool.play, I would like to know when that sound has done playing. I have some visual indicators that a specific sound is linked to, and I want to change them when done.

Some form of stream I can listen to for a change of state would be great.

**Comment by ukasz123** [comment]
Under the hood plugin uses (and tries to pretend to be) the [Soundpool API](https://developer.android.com/reference/android/media/SoundPool) from Android. There is no callback on playback finished available.
