### ISSUE TITLE
ios build fails: soundpool/soundpool-Swift.h not found

### ISSUE THREAD

**Issue by mtrivolli** [ukasz123/soundpool#12]
Trying to build my project on ios, I get the error 'fatal error: 'soundpool/soundpool-Swift.h' file not found'. 

I'm using  latest soundpool release: 0.5.1.

Any help?

**Comment by mtrivolli** [comment]
After looking around, I fixed the problem by modifying the Podfile in my project as described in [https://github.com/flutter/flutter/issues/16049#issuecomment-382629492](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)

**Comment by MarkBurvs** [comment]
Getting this same exact same issue using Soundpool 1.1.3 and the above fix doesn't work for me.
