### ISSUE TITLE
Much bigger delay once in a while

### ISSUE THREAD

**Issue by RohovDmytro** [ukasz123/soundpool#13]
```dart
    int m1 = new DateTime.now().millisecondsSinceEpoch;
    await soundPool.play(soundId);
    int m2 = new DateTime.now().millisecondsSinceEpoch;
    print('[' + _tickCounter.toString() + '] ' + (m2 - m1).toString());
   
```

![image](https://user-images.githubusercontent.com/1548235/65140506-5e238580-da17-11e9-931b-b4773e25c891.png)

Once in a while I have a huge delay while playing a sound (see 111 ms). This messes up my metronome timing. Any way I can help / improve / fix that? 

Thank you!

**Comment by ukasz123** [comment]
I wonder if it may be caused by the platform channels - they definitely add some delay and I'm not sure how much and if it is reliable.
If you really need a sound synchronized with a time then I'd suggest you to write it natively rather than relaying on Dart Timer. You can send events from native code using EventChannel to react to native ticks and update UI.

**Comment by rg4real** [comment]
> I wonder if it may be caused by the platform channels - they definitely add some delay and I'm not sure how much and if it is reliable.

Thank you for your (quick!) response, I appreciate it!

I might go with native code. What I've noticed that if I tap at any place on a screen the timing keep very low. As soon as a stop tapping — it goes up at have spikes in a coulple of seconds.

What's your opinion: can it be a hint on how I can fix and remove the spikes?..

**Comment by rg4real** [comment]
Btw, I want to clarify that timer itself works extremely reliable (<10 ms consistently). It's awaiting for a soundPool to play is not.

**Comment by ukasz123** [comment]
💭 Do you really need to `await` for `play()` to return? If your sound is really short then you won't have any use of soundId returned from that function.

I'd have test native code as well to see if the delay happens somewhere there.
