### ISSUE TITLE
ios build fails:"_OBJC_CLASS_$_FlutterMethodChannel", referenced from:       objc-class-ref in SwiftSoundpoolPlugin.o

### ISSUE THREAD

**Issue by yah0130** [ukasz123/soundpool#14]
i try to build my ios project but it fails
the exception is:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in SwiftSoundpoolPlugin.o
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in SwiftSoundpoolPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ukasz123** [comment]
Can you give me some more information about how you set up the Flutter project (the ios language), what Xcode version do you use and how are you trying to build it?
