### ISSUE TITLE
Soundpool marked as DISCONTINUED on pub.dev

### ISSUE THREAD

**Issue by roman-donchenko-tp** [ukasz123/soundpool#141]
I've noticed that the `soundpool` plugin is marked as DISCONTINUED on pub.dev.
Is there a chance of seeing this plugin live again?
Are there any alternative plugins?

**Comment by ukasz123** [comment]
It seems `audioplayers` have quite similar feature available: https://pub.dev/documentation/audioplayers/latest/audioplayers/AudioPool-class.html
