### ISSUE TITLE
ios: StreamType.alarm-> if device is in silent mode, should give sound!

### ISSUE THREAD

**Issue by daneed** [ukasz123/soundpool#16]
Hi.
I realized, that there is a TODO in your code, where this should be handled.
I did a modification, and I am curious about your opinion.
So, in SwiftSoundPoolPlugin.swift, I did this:

```
case "initSoundpool":
            let wrapper = SoundpoolWrapper()
            let index = wrappers.count

//my code, instead of your TODO >>
            let attributes = call.arguments as! NSDictionary
            let streamTypeIndex = attributes["streamType"] as! Int
            if streamTypeIndex == 1 {
                do {
                    try AVAudioSession.sharedInstance ().setCategory (AVAudioSession.Category.playback)
                    do {
                        try AVAudioSession.sharedInstance ().setActive (true)
                    } catch _ as NSError {

                    }
                } catch _ as NSError {

                }
            }
//my code, instead of your TODO <<
            wrappers.append(wrapper)
            result(index)
```

This solves the problem perfectly. So, what do you think?

Br, Daneed

**Comment by ukasz123** [comment]
Hello. Thank you for your commitment.

I haven't tested that solution but my first concern is if you can have two wrappers: one for `music` and one for `alarm` StreamType. Plugin should allow for both but maybe it isn't even possible in iOS world (if so I could just write a note about that).

**Comment by daneed** [comment]
Hi!
So, your concern, that you cannot have 2 different streamtype AVAudioSession at the same time...I am not a professional guy in this ios world, but as I understand, this is the concern. Maybe, I will try it...

An other thing: there is a second/or third parameter: options, in this setCategory, which can be: mixWithOthers. In my application, I should also set this, otherwise, ongoing music (like spotify) got muted as my customized soundpool is initialized.
And, there is an other options flag: duckOthers. Which means, that when my Alarm sounds, then the background music volume gets lower. But from now, I did not use it, because the music did not ducked back to the original volume after the alarm. I read, that there is a swift callback, "audioPlayerDidFinishPlaying", and in this, ducking can be disabled...but i yet did not know, how to wire in this callback.

But thanks, Daneed

**Comment by ukasz123** [comment]
@daneed I played a bit with AVAudioSession and it looks as if you cannot create multiple sessions for different audio stream types as in Android. So if you see reasonable to change the shared instance when the pool for `ring` or `alarm` type is requested then I can add such feature. Although it won't work the same way as on Android. Basically on iOS you can have only single type available for whole app.

**Comment by daneed** [comment]
Hi,
Yes, you are right, also according to this document,: 
https://developer.apple.com/documentation/avfoundation/avaudiosession
is described, that AVAudioSession is a singleton for the whole application, with one specific level.
There is no way to have 2 levels in IOS in the same app.

One, maybe possible solution is in my mind, (not for you, but i just thinking, that when it is possible, i will do this my customized SoundPool version):
- a common constructor for android and ios, without this StreamType parameter)
- a common global/static function, for android, and ios, to set the global default streamtype.
- an android specific constructor, with the StreamType parameter.
This pattern would highlight the difference between ios and android, in dart language-level.
This is not the most beautiful pattern, but what else could be done, if ios and android differs so much?
Btw, i don't know, that i can do this code magic in dart...i am beginner.

Btw, thanks for your help, this was really helpful for me to improve myself.

Daneed

**Comment by ukasz123** [comment]
I think I'll just update the documentation to highlight this difference.
