### ISSUE TITLE
After many sounds soundpool refuses to play anything.

### ISSUE THREAD

**Issue by MrVanosh** [ukasz123/soundpool#17]
Hi, I'm creating app and added mini-game to play music. User has 3x3 squares and when click one sound sample starts to play. I want to sounds overlap (first sound plays user clicks second square and they play together or user spam one sound and it overlapes). My approach for this is:
`onPressed: () async {
                      Soundpool pool = Soundpool();
                      await pool.loadAndPlay(sound1);
                    },` for every button.
sound1 is `sound1 = await rootBundle.load('assets/sounds/1.mp3')`
but after maybe 30 plays of some sound it won't play anymore. After that I don't receive any logs. I think my solution is wrong can you help me? Możemy pisać po polsku bo mój angielski jest trochę łamany, z góry dzięki za pomoc bo to bardzo ważne dla mnie :)

**Comment by ukasz123** [comment]
Problem probably lays in incorrect usage of the pool. The __correct__ was is to create a `Soundpool` only once/few times and also load sounds only once per session. This plugin attempts to cache sounds in memory to lower delays on playing. Here is a [simple example](https://github.com/ukasz123/soundpool/blob/master/example/lib/main_simple.dart#L28-L35) how it should be done in the intended way. I guess the documentation is not clear enough.

---
Problem polega na tym, że nie powinno się tworzyć wielu instancji `Soundpool` ani też nie powinno się _ładować_ tego samego pliku wiele razy. Ideą za tym pluginem jest cache'owanie dźwięku w pamięci, żeby ograniczyć opóźnienia. Należy załadować plik raz, a potem tylko wywoływać `play()` jak w [przykładzie](https://github.com/ukasz123/soundpool/blob/master/example/lib/main_simple.dart#L28-L35).

**Comment by MrVanosh** [comment]
Tak myślałem, czyli nie nie zrobię wielu dźwięków odtwarzających się w tym samym momencie? Np. Mam jeden przycisk ktoś go klika 10 razy i powinno włączyć się 10 tych samych dźwięków nakładając się na siebie. Próbowałem też ten problem rozwiązać przez audioplayers ale tam po kilku szybkich naciśnięciach przestaje reagować
i puszcza wszystko po kilku sekundach

**Comment by MrVanosh** [comment]
Albo mógłbym jakoś czyścić te instancje? Mam pomysł może stworzyć tablice 30 instancji soundpoola każdy przycisk by ładował do pojedynczej instancji dźwięk(byłby indeks co każde kliknięcie zwiększający się o 1) aż do osiągnięcia 30 wtedy wyczyszczenie tych instancji stworzenie nowych i wyzerowanie indeksu mogę tak zrobić ?

**Comment by MrVanosh** [comment]
Aa Ok widzę tego commita. Ta moja muzyka to pojedyncze 3 sekundowe dźwięki, jak mogę czyścić tym dispose to tak spróbuje z tablicą zrobić by potem dla każdego wykonał się dispose i może coś wykombinuje dzięki :)

**Comment by LH-CDT** [comment]
@MrVanosh Próbowałeś tworzyć `Soudpool` z parametrem `maxStreams` > 1? Alternatywnie możesz załadować ten sam plik kilkakrotnie i zbudować sobie listę odgłosów w cache. Następnie odtwarzasz dźwięki z cache z kolejnymi indeksami.
```dart
// ...
  _loadedSoundsIds = await Future.wait(List.generate(POOL_SIZE, (_)=> pool.load(soundAsset)));
  _lastPlayed = -1;
// ...
void _playSound(){
  _lastPlayed +=1;
 if (_lastPlayed == _loadedSoundsIds.length) {
   _lastPlayed = 0;
} 
pool.play(_lastPlayed);
}

**Comment by LH-CDT** [comment]
`dispose` spowoduje, że instancja `Soundpool` nie będzie się nadawać do użytku. Jeśli tylko chcesz usunąć dźwięki z cache, to odpowiednią metodą jest `release()`.

**Comment by MrVanosh** [comment]
A zaraz będę próbował, gdzieś mi się rzuciło w oczy, że maxstreams jest tylko do androida więc nie używałem bo na iOS też by było potrzebne ale posprawdzam i dam znać, dzięki :)

**Comment by MrVanosh** [comment]
@LH-CDT ahh maxstreams rozwiązał mój problem na Androidzie ale niestety na iOS nie działa to tak samo. Podczas trwania jednego dźwięku mogę włączyć drugi i będą grały razem ale jeden dźwięk nie może się nakładać, czyli jak kliknę kilka razy jeden dźwięk to powinien nakładać się na siebie, na Androidzie tak to działa ale na iOS niestety nie :( Spróbuje drugim sposobem co napisałeś

**Comment by MrVanosh** [comment]
Dzięki .release udało mi się znaleźć rozwiązanie na około, które mnie zadowala. Na pewno nie jest perfekcyjnie poprawne ale działa, dzięki za naprowadzenie, zostawiam je tutaj byście mogli się pośmiać :)

`  ByteData sound1, sound2, sound3, sound4, sound5, sound6, sound7, sound8, sound9;
  List<Soundpool> pools = [];
  int selectedPool = 0;

  void initPools() {
    for(int i=0; i<20; i++)
      pools.add(Soundpool());
  }

  Future loadSounds() async {
    sound1 = await rootBundle.load('assets/sounds/10.mp3');
    sound2 = await rootBundle.load('assets/sounds/2.mp3');
    sound3 = await rootBundle.load('assets/sounds/3.mp3');
    sound4 = await rootBundle.load('assets/sounds/4.mp3');
    sound5 = await rootBundle.load('assets/sounds/5.mp3');
    sound6 = await rootBundle.load('assets/sounds/6.mp3');
    sound7 = await rootBundle.load('assets/sounds/7.mp3');
    sound8 = await rootBundle.load('assets/sounds/8.mp3');
    sound9 = await rootBundle.load('assets/sounds/9.mp3');
  }

  Future playMusic(id) async {
    print(selectedPool);
    if(selectedPool == 19) {
      for(int i=0; i<20; i++) {
        await pools[i].release();
      }
      selectedPool = 0;
    }
    switch(id) {
      case 1: 
        await pools[selectedPool].loadAndPlay(sound1);
        break;
      case 2: 
        await pools[selectedPool].loadAndPlay(sound2);
        break;
      case 3: 
        await pools[selectedPool].loadAndPlay(sound3);
        break;
      case 4: 
        await pools[selectedPool].loadAndPlay(sound4);
        break;
      case 5: 
        await pools[selectedPool].loadAndPlay(sound5);
        break;
      case 6: 
        await pools[selectedPool].loadAndPlay(sound6);
        break;
      case 7: 
        await pools[selectedPool].loadAndPlay(sound7);
        break;
      case 8: 
        await pools[selectedPool].loadAndPlay(sound8);
        break;
      case 9: 
        await pools[selectedPool].loadAndPlay(sound9);
        break;
    }
    selectedPool++;
  }

  @override
  void initState() { 
    super.initState();
    initPools();
    loadSounds();
  }`

**Comment by MrVanosh** [comment]
Jednak ten iOS to trochę słaby wybór na tę wtyczkę :/ Nawet z tym maxStreams jak się klika wiele razy to niektóre nie chcą grać dopiero jak się pojedynczo kliknie więc to moje rozwiązanie lepiej działa tylko jak się już troche poklika to jakiś dźwięk potrafi z półseknudowym - sekundowym opóźnieniem się odpalić.

**Comment by ukasz123** [comment]
@MrVanosh W #19 wprowadziłem emulowanie funkcji `maxStreams` - plugin powinien teraz zezwalać na odtwarzanie tego samego dźwięku kilkakrotnie jednocześnie. 
Możesz podmienić sobie zależność w `pubspec.yaml` na 
```
  soundpool:
    git:
      url: git@github.com:ukasz123/soundpool.git
      ref: issue/17
```
