### ISSUE TITLE
Error running pod install after upgrading to 1.0.1

### ISSUE THREAD

**Issue by ahaboubi** [ukasz123/soundpool#24]
After upgrading from version 0.6.1 to 1.0.1, running on iOS generates a "Error running pod install".

Here's part of the stack:

`-> Fetching podspec for `soundpool_web` from `.symlinks/plugins/soundpool_web/ios`
    [!] No podspec found for `soundpool_web` in `.symlinks/plugins/soundpool_web/ios`
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
`

**Comment by ukasz123** [comment]
This should be resolved in `soundpool_web` version 1.0.2 which was published recently.
