### ISSUE TITLE
Feature request: Soundpool.stopAll()

### ISSUE THREAD

**Issue by lukepighetti** [ukasz123/soundpool#27]
Hi there,

I'm looking for a convenience method that stops all currently playing sounds. Thank you for your time.

**Comment by ukasz123** [comment]
Have you tried running `Future.wait(nowPlayingCollectedStreamIds.map((id)=>soundpool.stop(id))`? Honestly, I was building the plugin impressed by Android's [SoundPool API](https://developer.android.com/reference/android/media/SoundPool). There is no method to implement this feature in easy way so I'd have to add tracking streams on the native side (as I had to do for other platforms). I'd rather avoid doing that.

**Comment by lukepighetti** [comment]
I haven't but it seems reasonable so lets close this!
