### ISSUE TITLE
Sounds don't play on iOS physical device

### ISSUE THREAD

**Issue by lukepighetti** [ukasz123/soundpool#28]
Hey, I've got this working beautifully on iOS Simulator, but as soon as I try to run it on a physical device there is no audio. I don't see any reference to plist key entries or any other setup. Am I missing something?

**Comment by ukasz123** [comment]
That may be a problem at this time as I have no easy access to the real iOS device. I wonder if the [guide on Audio Session Categories and Modes](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionCategoriesandModes/AudioSessionCategoriesandModes.html#//apple_ref/doc/uid/TP40007875-CH10) may be helpful.

**Comment by lukepighetti** [comment]
It was apparently using ringer volume, so it was affected by having the silence switch on. Meanwhile other apps like YouTube were working perfectly.

**Comment by IlyaBlokh** [comment]
I have exactly same issue

**Comment by ukasz123** [comment]
I checked this problem on iOS phone. In my opinion it is related to the AVSession settings. Adding the following code to the AppDelegate.application didFinishLaunchingWithOptions
```swift
// Access the shared, singleton audio session instance
    let session = AVAudioSession.sharedInstance()
    do {
        // Configure the audio session for movie playback
        if #available(iOS 10.0, *) {
            try session.setCategory(AVAudioSession.Category.playback,
                                    mode: AVAudioSession.Mode.default,
                                    options: [])
        } else {
            // Fallback on earlier versions
            
        }
    } catch let error as NSError {
        print("Failed to set the audio session category and mode: \(error.localizedDescription)")
    }

```
I've found this snippet in the [Audio Session Programming Guide](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW7).

**Comment by henry2man** [comment]
@lukepighetti I'm playing sounds with no issues on both iOS physical devices and simulators using this package. 

I'm using StreamType.music and all works beautifully (also on Android devices).

@ukasz123 Maybe we can close this issue?

**Comment by lukepighetti** [comment]
> @lukepighetti I'm playing sounds with no issues on both iOS physical devices and simulators using this package.
> 
> I'm using StreamType.music and all works beautifully (also on Android devices).
> 
> @ukasz123 Maybe we can close this issue?

Please see https://github.com/ukasz123/soundpool/issues/28#issuecomment-608404772

**Comment by henry2man** [comment]
> > @lukepighetti I'm playing sounds with no issues on both iOS physical devices and simulators using this package.
> > I'm using StreamType.music and all works beautifully (also on Android devices).
> > @ukasz123 Maybe we can close this issue?
> 
> Please see [#28 (comment)](https://github.com/ukasz123/soundpool/issues/28#issuecomment-608404772)

@lukepighetti Reading the comment you indicate, I understood that the issue had been resolved, so I requested that it be closed.

**Comment by lukepighetti** [comment]
I don't have a project on hand to reproduce that this is fixed, perhaps a contributor can close this?

**Comment by ukasz123** [comment]
The AVAudioSession can be configured using SoundpoolOptionsIos when creating a Soundpool. Using `AudioSessionCategory.playback` would make sound be played even in _silent mode_.
