### ISSUE TITLE
Crashes with no error if .OGG files are used on iOS. Android works fine 

### ISSUE THREAD

**Issue by nicolasjon** [ukasz123/soundpool#33]
Crashes with no error  if .OGG files are used on iOS. Android works fine.
App returns to iPhone home screen.

**Comment by ukasz123** [comment]
I think iOS doesn't support OGG format for some reason.

**Comment by nicolasjon** [comment]
Yes. I think you are correct. Perhaps the doc could include that
info, might save a bit of confusion.
Thanks for a very useful package.
Nicolas
