### ISSUE TITLE
[Feature request] Volume control?

### ISSUE THREAD

**Issue by bockoblur** [ukasz123/soundpool#40]
Hello.
Is it possible to add a method/setting/parameter to set volume for playing sounds?
for example, 

```Dart
  Future<int> play(int soundId, {int repeat = 0, double rate = 1.0, double volume = 1.0}) async {
    // ...
  }
```

Thanks.

**Comment by misha** [comment]
Without this feature, it's impossible to set a sound without risking it playing at full volume for a split second.

**Comment by umanamente** [comment]
This feature is already there: you could set the volume for a `soundId` before playing:

```dart
player.setVolume(soundId: mySoundId, volume: 0.5);
```

**Comment by eximius313** [comment]
@ukasz123, shouldn't this issue be resolved?
