### ISSUE TITLE
[Feature request] enable mixing with background audio on iOS

### ISSUE THREAD

**Issue by deniza** [ukasz123/soundpool#44]
Hi,

Thanks for this great library. Easy to use and very efficient.

Currently if we play an audio file, background music stops. You can test this while playing some music on spotify. This can be prevented by calling two simple methods on AVAudioSession sharedInstance:

```swift
AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.ambient, options: AVAudioSession.CategoryOptions.mixWithOthers)
AVAudioSession.sharedInstance().setActive(true)
```

It would be nice to have this functionality in soundpool.

Cheers.

**Comment by ukasz123** [comment]
I strongly believe this feature should not be part of this plugin and implemented in the native code of the app instead (see #25).
I'd need some idea on how this feature should work on Android (web/MacOS).

**Comment by ukasz123** [comment]
@deniza 
The AVAudioSession can be configured using SoundpoolOptionsIos when creating a Soundpool. Hope it would work for you.

**Comment by fullflash** [comment]
yes this plugin does not support **AVAudioSessionCategoryOptions** SoundpoolOptionsIos has only setCategory and mode options.

not possible to use 
`audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord, withOptions: [AVAudioSessionCategoryOptions.MixWithOthers])
`
