### ISSUE TITLE
Playing stops on Android when playing 2 sounds

### ISSUE THREAD

**Issue by ahaboubi** [ukasz123/soundpool#49]
When playing a long sound (e.g. background music), and a second sound is played (like a notification), the first sound is stopped abruptly.

This issue is only present on Android. Works fine on iOS.

I'm using version 1.1.2.

**Comment by ukasz123** [comment]
Immediate solution would be either:
- set `maxStreams` in Soundpool constructor - it controls how many sounds can be played simultanously (if that helps then it means there is a bug on iOS).
- use separate Soundpools for notifications and background sound.

**Comment by ahaboubi** [comment]
Setting `maxStreams` works like a charm!

Thanks.
