### ISSUE TITLE
Plans to support Flutter 2.0?

### ISSUE THREAD

**Issue by sajunt4** [ukasz123/soundpool#58]
Hello there!

As the title says, there is any near plan to support Flutter 2.0?

Thank you!

**Comment by dsyrstad** [comment]
I'm successfully using soundpool 1.1.3 on Flutter 2.0.1 (stable) Android as of today.

**Comment by sajunt4** [comment]
The problem is that it conflicts with Permission Handler pluggin, that lately has been updated to support Flutter 2.0 and Soundpool still uses an old version of it.

They should update that dependency in order to solve the problem.

**Comment by sajunt4** [comment]
Well, `pub get` actually told me something about `soundpool` and `permission_handler`, but maybe because it found that those two differ on something (not actually 'soundpool' depending on 'permission_handler'. Badly interpreted on my side.

As there actually exists a pull request to solve those problems, I'm gonna close this issue.
Thanks!
