### ISSUE TITLE
Need plugin_platform_interface 1.0.0 updated to ^2.0.0

### ISSUE THREAD

**Issue by nezoat** [ukasz123/soundpool#59]
I'm having to use soundpool 0.5.4 because newer versions of soundpool have a dependency on plugin_platform_interface 1.0.0.  Many of my other plugins are using plugin_platform_interface ^2.0.0 now.  Any chance soundpool can be updated to ^2.0.0 ?   All ~50 of my project plugins are latest versions, except soundpool.

**Comment by ukasz123** [comment]
Fixed in 2.0.0-nullsafety.0

**Comment by nezoat** [comment]
Fantastic!
