### ISSUE TITLE
How can i play local audio file on android ?

### ISSUE THREAD

**Issue by liaofuyou** [ukasz123/soundpool#6]
Very thanks you made this project, it is help a lot.

but i got a issue, i can play local audio file on iOS, but id is not work on android . this is my code:
`
      // file：  /data/data/me.ajax.test/app_flutter/audios/sound.mp3
      Soundpool pool = Soundpool(streamType: StreamType.music);
      return pool.loadAndPlayUri(Uri.file(file).toString());
`

**Comment by ukasz123** [comment]
Thank you for pointing that out.
I figured out that on Android I should wait for callback to be triggered to be sure that sound is actually ready. I made necessary changes and the method you are using should work in `0.4.1`.
