### ISSUE TITLE
Playing Sound In Background iOS (works on Android)

### ISSUE THREAD

**Issue by bayhall** [ukasz123/soundpool#62]
We're using your sound plugin to play a beep every second for a breathing app (inhale/exhale) - for every second we play one beep, on the change from inhale to exhale we play an alternate pitched beep. Both sounds are loaded in soundloop and cached.

Is it possible to play the sounds in the background if the app is still running but the user goes swipes the app to the background? At the moment the app still ticks and the 1 second period timer keeps running, but the sounds generated by soundpool stops? - this is iOS only.

Could be related - when we bring the app back into the foreground, the beep which was last played is lost - to fix this we've had to run _loadSounds() again when the app is "resumed" - using the [WidgetsBindingObserver](https://stackoverflow.com/questions/51835039/how-do-i-check-if-the-flutter-application-is-in-the-foreground-or-not)

What I also noticed, is that in debug mode attached to android studio, the sound plays in the background - but when we go to profile or release the sounds stop when in the background.

I've tried to configure some background settings in the configuration within Xcode without luck.

Thanks in advance for any tips or tricks.

**Comment by boskokg** [comment]
use this:

  soundpool:
    git:
      url: https://github.com/boskokg/soundpool/
      path: soundpool
      ref: master

**Comment by ukasz123** [comment]
The AVAudioSession can be configured using [SoundpoolOptionsIos](https://pub.dev/documentation/soundpool/latest/soundpool/SoundpoolOptionsIos-class.html) when creating a `Soundpool`.
