### ISSUE TITLE
Severe lag in playing multiple UIs at the same time

### ISSUE THREAD

**Issue by yy1300326388** [ukasz123/soundpool#64]
Playing multiple audio at the same time will freeze the UI problem, as shown in the two videos below, I have solved this problem, see pr for details

- Before repair

https://user-images.githubusercontent.com/8764899/115115221-cbb5e000-9fc5-11eb-9d40-8b8609d972b1.mp4

- After repair

https://user-images.githubusercontent.com/8764899/115115235-d7090b80-9fc5-11eb-8d74-904f9f0803b0.mp4

- Code

![image](https://user-images.githubusercontent.com/8764899/115115257-00c23280-9fc6-11eb-8a1b-fd8eff91e821.png)

**Comment by ukasz123** [comment]
@yy1300326388 Thank you for the solution. It may be good idea to perform all of audio operations on separate thread.

Have you tried to set `maxStreams = 9` in the `Soundpool` constructor.

**Comment by yy1300326388** [comment]
@ukasz123  
The number of simultaneous playback of my scene is dynamic, it has nothing to do with maxStreams, and I set it during the first initialization.

I tried the settings but it does not work.
