### ISSUE TITLE
False error warning

### ISSUE THREAD

**Issue by johnareid54** [ukasz123/soundpool#74]
Any plans on getting rid of this annoying message?

**'Soundpool' is deprecated and shouldn't be used. Use `fromOptions` instead.
Try replacing the use of the deprecated member with the replacement.**

This is the line that is causing the message:

**static final Soundpool _soundpool = Soundpool();**

**Comment by ukasz123** [comment]
It's intended. I deprecated the default constructor. Please, use the `fromOptions` now. None of parameters are required. I'll clarify that in the documentation.

**Comment by johnareid54** [comment]
Thanks, I understand it now!
