### ISSUE TITLE
Call release()

### ISSUE THREAD

**Issue by johnareid54** [ukasz123/soundpool#75]
Could you expand on the comment in readme:

**DO NOT leave sounds loaded in memory when no longer used; DO call release() or dispose() when sounds are no longer useful.**

I use Soundpool to play and repeat in a loop small mp3 files (less than 1 second in length). What should I do if I play file **a** first then move on to file **b** and so on.  I am not sure where to use release().

**Comment by ukasz123** [comment]
You should call `release()` when you are sure you won't need loaded sounds anymore. The example would be Soundpool holding sounds for some level of the game. When players finishes it and moves to the next one you may release that Soundpool and create new one. 
On the other hand you may have another Soundpool holding sounds for UI actions feedback. That instance would be created at the start of the game and kept forever although it may be a good idea to load sounds when the game is resumed (being moved to the foreground) and release them when it is paused or stopped (see [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html)).

**Comment by johnareid54** [comment]
Thanks @ukasz123  - great package, working well!
