### ISSUE TITLE
Upgrade to use Flutter embedding V2

### ISSUE THREAD

**Issue by basnetjiten** [ukasz123/soundpool#81]
The plugins `soundpool` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by ukasz123** [comment]
It was updated in version [`2.2.0`](https://pub.dev/packages/soundpool/versions/2.2.0).

**Comment by leventkantaroglu** [comment]
Still getting same error with `2.2.0`

**Comment by ukasz123** [comment]
> Still getting same error with `2.2.0`

@leventkantaroglu You need to clean the project so the tools would generate new `GeneratedPluginRegistrant.java` file.

**Comment by leventkantaroglu** [comment]
> You need to clean the project so the tools would generate new GeneratedPluginRegistrant.java file.

Which cleaning steps do you suggest? flutter clean, removing pods, cleaning in android studio etc none of them worked. I also cleaned pub cache folder. thanks
