### ISSUE TITLE
 inconsistent sounds when playing sound at a high rate.

### ISSUE THREAD

**Issue by Wamwea** [ukasz123/soundpool#85]
I'm making a metronome app and at higher tempos.(200 and above beats per minute) the sounds become inconsistent. And sometimes on ios the sound is skipped entirely. Is there any way to combat this?

D/AudioTrack(22919): createTrack_l(3643): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 17408

**Comment by Wamwea** [comment]
Managed to fix this issue

**Comment by novas1r1** [comment]
@Wamwea How did you fix that? I'm having the same problem :(((

**Comment by zhanzhenchao** [comment]
@Wamwea I want to ask this question, too
